<?php

namespace App\Services;

use Barryvdh\DomPDF\Facade\Pdf;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

// Turns the neutral "report" array built by Admin/FarmerReportController into
// an actual PDF or XLSX file. Both formats are driven off the exact same
// $report shape so a report only has to be assembled once:
//
// [
//   'title'       => string,
//   'meta'        => ['generated_by' => .., 'generated_at' => .., 'filters' => ['Period' => ..]],
//   'summary'     => [['label' => .., 'value' => .. (already display-formatted)], ...],
//   'sections'    => [
//       ['heading' => ?string, 'columns' => [['key','label','type']], 'rows' => [assoc, ...]],
//   ],
//   'orientation' => 'portrait'|'landscape',
// ]
//
// column type is one of: string, number, decimal, currency, date — it drives
// PDF text formatting and the Excel cell's raw value + number format.
class ReportExportService
{
    public function pdf(array $report): \Barryvdh\DomPDF\PDF
    {
        $displayReport = $report;

        foreach ($displayReport['sections'] as &$section) {
            foreach ($section['rows'] as &$row) {
                foreach ($section['columns'] as $col) {
                    $row[$col['key']] = $this->formatForDisplay($row[$col['key']] ?? null, $col['type']);
                }
            }
        }
        unset($section, $row);

        $pdf = Pdf::loadView('reports.pdf', $displayReport);
        $pdf->setPaper('a4', $report['orientation'] ?? 'portrait');

        return $pdf;
    }

    public function xlsx(array $report): Spreadsheet
    {
        $spreadsheet = new Spreadsheet();
        $sheet       = $spreadsheet->getActiveSheet();
        $sheet->setTitle(mb_substr($report['title'], 0, 31));

        $row = 1;

        $sheet->setCellValue("A{$row}", 'SokoMoja');
        $sheet->getStyle("A{$row}")->getFont()->setBold(true)->setSize(16);
        $row++;

        $sheet->setCellValue("A{$row}", $report['title']);
        $sheet->getStyle("A{$row}")->getFont()->setBold(true)->setSize(12);
        $row++;

        $sheet->setCellValue("A{$row}", 'Generated by: ' . $report['meta']['generated_by']);
        $row++;
        $sheet->setCellValue("A{$row}", 'Generated on: ' . $report['meta']['generated_at']);
        $row++;

        foreach ($report['meta']['filters'] as $label => $value) {
            $sheet->setCellValue("A{$row}", "{$label}: {$value}");
            $row++;
        }

        $row++;

        if (!empty($report['summary'])) {
            $sheet->setCellValue("A{$row}", 'Summary');
            $sheet->getStyle("A{$row}")->getFont()->setBold(true)->setSize(12);
            $row++;

            foreach ($report['summary'] as $card) {
                $sheet->setCellValue("A{$row}", $card['label']);
                $sheet->setCellValue("B{$row}", $card['value']);
                $sheet->getStyle("A{$row}")->getFont()->setBold(true);
                $row++;
            }

            $row++;
        }

        foreach ($report['sections'] as $section) {
            if (!empty($section['heading'])) {
                $sheet->setCellValue("A{$row}", $section['heading']);
                $sheet->getStyle("A{$row}")->getFont()->setBold(true)->setSize(11);
                $row++;
            }

            $headerRow = $row;
            $col = 'A';
            foreach ($section['columns'] as $column) {
                $sheet->setCellValue("{$col}{$row}", $column['label']);
                $col++;
            }
            $sheet->getStyle("A{$headerRow}:" . chr(64 + count($section['columns'])) . $headerRow)
                ->getFont()->setBold(true);
            $sheet->getStyle("A{$headerRow}:" . chr(64 + count($section['columns'])) . $headerRow)
                ->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB('E8F5E9');
            $row++;

            if (empty($section['rows'])) {
                $sheet->setCellValue("A{$row}", 'No data for the selected filters.');
                $row++;
            }

            foreach ($section['rows'] as $dataRow) {
                $col = 'A';
                foreach ($section['columns'] as $column) {
                    $value = $dataRow[$column['key']] ?? null;
                    $cell  = "{$col}{$row}";

                    if (in_array($column['type'], ['number', 'decimal', 'currency'], true)) {
                        $sheet->setCellValue($cell, (float) $value);
                        $sheet->getStyle($cell)->getNumberFormat()->setFormatCode(
                            match ($column['type']) {
                                'currency' => '#,##0.00',
                                'decimal'  => '#,##0.00',
                                default    => '#,##0',
                            }
                        );
                    } else {
                        $sheet->setCellValue($cell, (string) $value);
                    }

                    $col++;
                }
                $row++;
            }

            $row++;
        }

        foreach (range('A', 'J') as $columnLetter) {
            $sheet->getColumnDimension($columnLetter)->setAutoSize(true);
        }

        return $spreadsheet;
    }

    public function streamXlsx(Spreadsheet $spreadsheet, string $filename): \Symfony\Component\HttpFoundation\StreamedResponse
    {
        $writer = new Xlsx($spreadsheet);

        return response()->streamDownload(function () use ($writer) {
            $writer->save('php://output');
        }, $filename, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ]);
    }

    private function formatForDisplay(mixed $value, string $type): string
    {
        if ($value === null) {
            return '—';
        }

        return match ($type) {
            'currency' => 'KES ' . number_format((float) $value, 2),
            'decimal'  => number_format((float) $value, 2),
            'number'   => number_format((float) $value),
            default    => (string) $value,
        };
    }
}
