// ReportView — shared by AdminReports + FarmerReports.
// Renders the neutral { title, meta, summary, sections } shape returned by
// every report endpoint (zone-performance, user-activity, top-products,
// inventory, sales) so the on-screen report only has to be built once.

function formatCell(value, type) {
  if (value === null || value === undefined || value === "") return "—";

  switch (type) {
    case "currency":
      return `KES ${Number(value).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    case "decimal":
      return Number(value).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    case "number":
      return Number(value).toLocaleString("en-KE");
    default:
      return String(value);
  }
}

function SummaryCards({ summary }) {
  if (!summary || summary.length === 0) return null;

  return (
    <div className="row g-3 mb-4 sm-fade-in">
      {summary.map((card, i) => (
        <div className="col-6 col-md-3" key={i}>
          <div className="sm-stat-card">
            <div className="sm-stat-value" style={{ fontSize: "1.15rem" }}>{card.value}</div>
            <div className="sm-stat-label">{card.label}</div>
          </div>
        </div>
      ))}
    </div>
  );
}

function Section({ section }) {
  return (
    <div className="card border-0 shadow-sm sm-fade-in mb-3">
      {section.heading && (
        <div className="px-3 pt-3">
          <h6 className="mb-0 text-success fw-bold">{section.heading}</h6>
        </div>
      )}
      <div className="table-responsive">
        <table className="table table-hover align-middle table-striped-columns mb-0">
          <thead>
            <tr>
              {section.columns.map((col) => (
                <th key={col.key} className={col.type !== "string" ? "text-end" : ""}>{col.label}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {section.rows.length === 0 ? (
              <tr>
                <td colSpan={section.columns.length} className="text-center text-muted py-4">
                  No data for the selected filters.
                </td>
              </tr>
            ) : (
              section.rows.map((row, i) => (
                <tr key={i}>
                  {section.columns.map((col) => (
                    <td key={col.key} className={col.type !== "string" ? "text-end" : ""}>
                      {formatCell(row[col.key], col.type)}
                    </td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default function ReportView({ report }) {
  if (!report) return null;

  return (
    <div>
      <div className="d-flex flex-wrap justify-content-between align-items-baseline mb-2">
        <h5 className="mb-0">{report.title}</h5>
        <div className="text-muted small">
          Generated by {report.meta.generated_by} &middot; {report.meta.generated_at}
        </div>
      </div>

      {Object.entries(report.meta.filters).length > 0 && (
        <div className="text-muted small mb-3">
          {Object.entries(report.meta.filters).map(([label, value]) => `${label}: ${value}`).join("  ·  ")}
        </div>
      )}

      <SummaryCards summary={report.summary} />

      {report.sections.map((section, i) => (
        <Section section={section} key={i} />
      ))}
    </div>
  );
}
