<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page { margin: 26px 30px; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1a1a1a; }

    .brand { font-size: 20px; font-weight: 700; color: #1B5E20; }
    .brand span { color: #43A047; }
    .report-title { font-size: 15px; font-weight: 700; margin-top: 2px; }

    .meta { margin-top: 10px; margin-bottom: 14px; font-size: 10px; color: #444; }
    .meta table { width: 100%; border-collapse: collapse; }
    .meta td { padding: 1px 0; vertical-align: top; }
    .meta .meta-label { font-weight: 700; width: 110px; }

    .summary-title { font-size: 12px; font-weight: 700; margin: 10px 0 6px; color: #1B5E20; }
    .summary-grid { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
    .summary-grid td {
        border: 1px solid #C8E6C9; background: #E8F5E9; padding: 6px 8px;
        width: 25%; vertical-align: top;
    }
    .summary-label { font-size: 9px; text-transform: uppercase; color: #2E7D32; font-weight: 700; }
    .summary-value { font-size: 12px; font-weight: 700; color: #1a1a1a; margin-top: 2px; }

    .section-heading { font-size: 12px; font-weight: 700; margin: 14px 0 6px; color: #1B5E20; }

    table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
    table.data-table thead { display: table-header-group; }
    table.data-table th {
        background: #2E7D32; color: #fff; font-size: 9.5px; text-align: left;
        padding: 5px 6px; font-weight: 700;
    }
    table.data-table td {
        font-size: 9.5px; padding: 4px 6px; border-bottom: 1px solid #e0e0e0;
    }
    table.data-table tr:nth-child(even) td { background: #F7FAF7; }
    .text-right { text-align: right; }
    .empty-row td { text-align: center; color: #888; padding: 10px; font-style: italic; }

    .footer { position: fixed; bottom: -16px; left: 0; right: 0; font-size: 8px; color: #999; text-align: center; }
</style>
</head>
<body>

    <div class="brand">Soko<span>Moja</span></div>
    <div class="report-title">{{ $title }}</div>

    <div class="meta">
        <table>
            <tr><td class="meta-label">Generated by</td><td>{{ $meta['generated_by'] }}</td></tr>
            <tr><td class="meta-label">Generated on</td><td>{{ $meta['generated_at'] }}</td></tr>
            @foreach ($meta['filters'] as $label => $value)
                <tr><td class="meta-label">{{ $label }}</td><td>{{ $value }}</td></tr>
            @endforeach
        </table>
    </div>

    @if (!empty($summary))
        <div class="summary-title">Summary</div>
        <table class="summary-grid">
            <tr>
            @foreach ($summary as $i => $card)
                @if ($i > 0 && $i % 4 === 0)
                    </tr><tr>
                @endif
                <td>
                    <div class="summary-label">{{ $card['label'] }}</div>
                    <div class="summary-value">{{ $card['value'] }}</div>
                </td>
            @endforeach
            </tr>
        </table>
    @endif

    @foreach ($sections as $section)
        @if (!empty($section['heading']))
            <div class="section-heading">{{ $section['heading'] }}</div>
        @endif
        <table class="data-table">
            <thead>
                <tr>
                    @foreach ($section['columns'] as $col)
                        <th class="{{ $col['type'] !== 'string' ? 'text-right' : '' }}">{{ $col['label'] }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @forelse ($section['rows'] as $row)
                    <tr>
                        @foreach ($section['columns'] as $col)
                            <td class="{{ $col['type'] !== 'string' ? 'text-right' : '' }}">{{ $row[$col['key']] }}</td>
                        @endforeach
                    </tr>
                @empty
                    <tr class="empty-row"><td colspan="{{ count($section['columns']) }}">No data for the selected filters.</td></tr>
                @endforelse
            </tbody>
        </table>
    @endforeach

    <div class="footer">SokoMoja &middot; Generated {{ $meta['generated_at'] }} &middot; Page <span></span></div>

</body>
</html>
